// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmjtchtogoeuxovuodvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtanRjaHRvZ29ldXhvdnVvZHZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMTU5ODIsImV4cCI6MjA2Njc5MTk4Mn0.LPGf28-cLhIAIKvjvsqMA8JMqQyYPkB8gA1mx5h9yxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);